### ISSUE TITLE
Nostxからnostterに飛ばせるようにしたい

### ISSUE THREAD

**Issue by imksoo** [ShinoharaTa/Nostx#1]
IrisとSnortだけでなく、nostterにもリダイレクトできるように追加してほしい。

**Comment by ShinoharaTa** [comment]
@imksoo 
nostterの向き先指定了解。
noteの向き先は指定可能ですかね？
userリンクは確認しました

**Comment by ShinoharaTa** [comment]
Noteもいけることがわかりました！
実装します

**Comment by ShinoharaTa** [comment]
実装しました
