### ISSUE TITLE
NIP-05 addressの対応

### ISSUE THREAD

**Issue by kojira** [ShinoharaTa/Nostx#2]
NIP-05 addressに対応して
https://nostx.shino3.net/kojira@nostr.kojira.net
などでも開けるようにして欲しい

https://<domain>/.well-known/nostr.json?name=<local-part>
にアクセスしてjsonをパースしてhexのアドレスをnpubに変換すればどのクライアントでもだいたい行けそう

**Comment by ShinoharaTa** [comment]
対応しました。
URL方式は以下の通り

https://nostx.shino3.net/user?u=shino3@nostr.shino3.net
https://nostx.shino3.net/user?u=mattn.github.io

**Comment by ShinoharaTa** [comment]
対応完了！
https://nostx.io/[nip-05] でも使えるようになりました
